/// A description of a Rune pipeline.
record pipeline {
    /// The list of nodes in this pipeline.
    nodes: list<node>,
}

/// A single node in the pipeline.
record node {
    /// A string that uniquely identifies this node.
    id: string,
    /// A list of the nodes this node depends on.
    depends-on: list<string>,
    /// Arguments that should be passed to this node while typechecking and
    /// evaluating it, as a list of key-value pairs.
    arguments: list<tuple<string, string>>,
}

/// Get the pipeline this.
get-pipeline: function() -> pipeline
